import portsData from "@/lib/ports-data.json";

const TIER_LABEL: Record<string, string> = { safe: "SAFE", review: "REVIEW", manual: "MANUAL" };

export function PortPlan({ slug }: { slug: string }) {
  const entry = (portsData as Record<string, { hasPatch: boolean; transforms: { id: string; title: string; tier: string; files: number }[] }>)[slug];
  if (!entry || entry.transforms.length === 0) return null;

  return (
    <section className="block" data-reveal style={{ borderBottom: 0 }}>
      <div className="sec-head">
        <h2>Port plan</h2>
        <span className="id">generated by the FoldReady CLI · dry run</span>
      </div>
      <p style={{ color: "var(--dim)", fontSize: 14, maxWidth: "60ch", marginBottom: 20 }}>
        Ready-to-review changes that move this app toward the foldable contract: scene
        lifecycle, Parallel View opt-in, sidebar navigation. Review the diff, then apply
        with <code>foldready port --apply</code>.
      </p>
      <div style={{ display: "flex", flexDirection: "column", gap: 10, marginBottom: 20 }}>
        {entry.transforms.map((t) => (
          <div key={t.id} className="frow" style={{ gridTemplateColumns: "84px 1fr auto" }}>
            <span className={`tier ${t.tier}`}>{TIER_LABEL[t.tier] ?? t.tier}</span>
            <span className="chk">{t.title} <span style={{ color: "var(--dim)" }}>· {t.files} file{t.files === 1 ? "" : "s"}</span></span>
            <span />
          </div>
        ))}
      </div>
      <div className="band-acts" style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>
        {entry.hasPatch ? (
          <a className="btn btn-pri" href={`/ports/${slug}/port.patch`} download>Download port patch</a>
        ) : (
          <span className="chip ready">guidance only — no patch edits to apply</span>
        )}
        <a className="btn btn-sec" href={`/ports/${slug}/porting-report.md`} download>Full porting report</a>
      </div>
    </section>
  );
}
