import Foundation

enum Transforms {

    // MARK: - Safe tier

    static func removeFullScreen(_ input: TransformInput) -> Patch {
        var edits: [FileEdit] = []
        var notes: [String] = []
        let pattern = #"\s*<key>UIRequiresFullScreen</key>\s*(?:<(?:true|false)/>|<string>[^<]*</string>)?"#
        let regex = try? NSRegularExpression(pattern: pattern, options: [.dotMatchesLineSeparators])
        for plist in input.plists {
            guard plist.content.contains("UIRequiresFullScreen") else { continue }
            guard let regex else { continue }
            let ns = plist.content as NSString
            let range = NSRange(location: 0, length: ns.length)
            let cleaned = regex.stringByReplacingMatches(in: plist.content, options: [], range: range, withTemplate: "")
            let collapsed = cleaned.replacingOccurrences(of: "\n{3,}", with: "\n\n", options: .regularExpression)
            guard collapsed != plist.content else { continue }
            edits.append(FileEdit(path: plist.path, before: plist.content, after: collapsed))
            notes.append("Removed UIRequiresFullScreen from \(plist.path) — opts the app into Parallel View / resizability.")
        }
        return Patch(transformId: "remove-fullscreen", title: "Remove UIRequiresFullScreen opt-out",
            tier: .safe, edits: edits, newFiles: [:], notes: notes)
    }

    static func sidebarOptIn(_ input: TransformInput) -> Patch {
        var edits: [FileEdit] = []
        var notes: [String] = []
        let subclass = try? NSRegularExpression(pattern: #"class\s+\w+\s*:\s*[^\{]*UITabBarController"#, options: [])
        let superCall = "super.viewDidLoad()"
        let override = "override func viewDidLoad()"

        for file in input.swiftFiles {
            guard let subclass, subclass.firstMatch(in: file.content, range: NSRange(file.content.startIndex..., in: file.content)) != nil else { continue }
            if file.content.contains("tabSidebar") || file.content.contains("preferredPlacement") {
                notes.append("\(file.path): sidebar already opted in.")
                continue
            }
            var lines = file.content.components(separatedBy: .newlines)
            var insertAt: Int?
            if let idx = lines.firstIndex(where: { $0.range(of: superCall) != nil }) {
                insertAt = idx + 1
            } else if let idx = lines.firstIndex(where: { $0.range(of: override) != nil }) {
                insertAt = idx + 1
            }
            if let at = insertAt {
                let indentation = lines[at - 1].prefix(while: { $0 == " " || $0 == "\t" })
                lines.insert("\(indentation)mode = .tabSidebar", at: at)
                lines.insert("\(indentation)sidebar.preferredPlacement = .sidebar", at: at + 1)
                edits.append(FileEdit(path: file.path, before: file.content, after: lines.joined(separator: "\n")))
                notes.append("\(file.path): tab bar becomes a sidebar on wide canvases (mode = .tabSidebar).")
            } else {
                notes.append("\(file.path): add a viewDidLoad override to set mode = .tabSidebar and sidebar.preferredPlacement = .sidebar.")
            }
        }
        return Patch(transformId: "sidebar-optin", title: "UIKit tab bar → sidebar opt-in",
            tier: .safe, edits: edits, newFiles: [:], notes: notes)
    }

    // MARK: - Review tier

    static func sceneLifecycle(_ input: TransformInput) -> Patch {
        let swiftuiApp = input.swiftFiles.contains { $0.content.contains(": App") && $0.content.contains("import SwiftUI") }
        let uikitApp = input.swiftFiles.contains { $0.content.contains("@UIApplicationMain") || ($0.content.contains("@main") && $0.content.contains("UIApplicationDelegate")) }
        let hasScene = input.swiftFiles.contains {
            $0.content.contains("UIWindowSceneDelegate") || $0.content.contains("UISceneDelegate") || $0.content.contains("UISceneConfiguration")
        }
        guard uikitApp && !hasScene && !swiftuiApp else {
            return Patch(transformId: "scene-lifecycle", title: "UIScene lifecycle",
                tier: .review, edits: [], newFiles: [:],
                notes: hasScene || swiftuiApp ? ["Scene lifecycle already present."] : ["Not a UIKit app-delegate app; nothing to do."])
        }

        let sceneDelegate = """
        import UIKit

        // Generated by FoldReady — migrate your AppDelegate's window setup here.
        // See Apple Technote TN3187 for the full UIScene migration.
        class SceneDelegate: UIResponder, UIWindowSceneDelegate {

            var window: UIWindow?

            func scene(_ scene: UIScene, willConnectTo session: UISceneSession,
                       options connectionOptions: UIScene.ConnectionOptions) {
                guard let windowScene = scene as? UIWindowScene else { return }
                let window = UIWindow(windowScene: windowScene)
                // TODO: set the app's real root view controller here (previously built in AppDelegate).
                window.rootViewController = UIViewController()
                window.makeKeyAndVisible()
                self.window = window
            }
        }
        """
        let manifest = """
        \t<key>UIApplicationSceneManifest</key>
        \t<dict>
        \t\t<key>UIApplicationSupportsMultipleScenes</key>
        \t\t<false/>
        \t\t<key>UISceneConfigurations</key>
        \t\t<dict>
        \t\t\t<key>UIWindowSceneSessionRoleApplication</key>
        \t\t\t<array>
        \t\t\t\t<dict>
        \t\t\t\t\t<key>UISceneConfigurationName</key>
        \t\t\t\t\t<string>Default Configuration</string>
        \t\t\t\t\t<key>UISceneDelegateClassName</key>
        \t\t\t\t\t<string>$(PRODUCT_MODULE_NAME).SceneDelegate</string>
        \t\t\t\t</dict>
        \t\t\t</array>
        \t\t</dict>
        \t</dict>
        """

        var edits: [FileEdit] = []
        var notes: [String] = []
        if let plist = input.plists.first(where: { !$0.path.contains("Tests") }) {
            if !plist.content.contains("UIApplicationSceneManifest") {
                let after = plist.content.replacingOccurrences(
                    of: #"</dict>\s*</plist>"#,
                    with: "\(manifest)\n</dict>\n</plist>",
                    options: .regularExpression)
                edits.append(FileEdit(path: plist.path, before: plist.content, after: after))
                notes.append("Added UIApplicationSceneManifest to \(plist.path).")
            }
        }
        notes.append("UIScene lifecycle is REQUIRED from the iOS 27 SDK — apps without it fail to launch (TN3187).")
        notes.append("Set the real rootViewController in SceneDelegate (currently a placeholder).")
        return Patch(transformId: "scene-lifecycle", title: "Migrate to UIScene lifecycle",
            tier: .review, edits: edits, newFiles: ["SceneDelegate.swift": sceneDelegate], notes: notes)
    }

    static func screenBounds(_ input: TransformInput) -> Patch {
        var edits: [FileEdit] = []
        var notes: [String] = []
        // Exact full-bleed patterns that are safe to replace.
        let fullBoth = try? NSRegularExpression(pattern: #"\.frame\(width:\s*UIScreen\.main\.bounds\.width\s*,\s*height:\s*UIScreen\.main\.bounds\.height\s*\)"#, options: [])
        let fullWidth = try? NSRegularExpression(pattern: #"\.frame\(width:\s*UIScreen\.main\.bounds\.width\s*\)"#, options: [])
        let boundsRead = try? NSRegularExpression(pattern: #"UIScreen\.main\.bounds"#, options: [])

        for file in input.swiftFiles {
            guard file.content.contains("UIScreen.main.bounds") else { continue }
            var after = file.content
            if let fullBoth {
                after = fullBoth.stringByReplacingMatches(in: after, options: [], range: NSRange(after.startIndex..., in: after), withTemplate: ".frame(maxWidth: .infinity, maxHeight: .infinity)")
            }
            if let fullWidth {
                after = fullWidth.stringByReplacingMatches(in: after, options: [], range: NSRange(after.startIndex..., in: after), withTemplate: ".frame(maxWidth: .infinity)")
            }
            let remaining = boundsRead?.numberOfMatches(in: after, range: NSRange(after.startIndex..., in: after)) ?? 0
            if remaining > 0 {
                notes.append("\(file.path): \(remaining) UIScreen.main.bounds read(s) remain — replace with the scene's effective geometry.")
            }
            if after != file.content {
                edits.append(FileEdit(path: file.path, before: file.content, after: after))
            }
        }
        notes.append("UIScreen.main is deprecated in iOS 27; reads must come from the window scene / effective geometry.")
        return Patch(transformId: "screen-bounds", title: "Replace UIScreen.main.bounds",
            tier: .review, edits: edits, newFiles: [:], notes: notes)
    }

    static func adaptiveNavigation(_ input: TransformInput) -> Patch {
        var edits: [FileEdit] = []
        var notes: [String] = []
        let stackOpen = "NavigationStack {"

        for file in input.swiftFiles {
            guard file.content.contains(stackOpen), !file.content.contains("NavigationSplitView") else { continue }
            let whole = file.content
            guard let openIdx = whole.range(of: stackOpen)?.lowerBound else { continue }
            guard let closeIdx = matchingCloseBrace(whole, openBrace: openIdx) else {
                notes.append("\(file.path): could not brace-match the root NavigationStack; wrap manually.")
                continue
            }
            let prefix = String(whole[..<openIdx])
            let block = String(whole[openIdx...closeIdx])
            let suffix = String(whole[whole.index(after: closeIdx)...])
            let after = prefix + "NavigationSplitView { " + block + " } detail: { Color.clear }" + suffix
            edits.append(FileEdit(path: file.path, before: whole, after: after))
            notes.append("\(file.path): wrapped the root NavigationStack in a NavigationSplitView — the list becomes the sidebar, detail is a placeholder.")
            notes.append("\(file.path): move selection-driven content into the detail column and add .adaptiveSidebar() at the scene root.")
        }
        if edits.isEmpty {
            notes.append("No top-level NavigationStack without an existing NavigationSplitView found.")
        }
        return Patch(transformId: "adaptive-navigation", title: "NavigationStack → NavigationSplitView",
            tier: .review, edits: edits, newFiles: [:], notes: notes)
    }

    // MARK: - Manual tier

    static func statePreservation(_ input: TransformInput) -> Patch {
        var notes: [String] = []
        let sceneStorage = try? NSRegularExpression(pattern: #"@SceneStorage|restorationIdentifier|preservesSelectionInNavigationStack"#, options: [])
        for file in input.swiftFiles {
            if file.content.contains("List") || file.content.contains("ScrollView") {
                let has = sceneStorage?.firstMatch(in: file.content, range: NSRange(file.content.startIndex..., in: file.content)) != nil
                if !has {
                    notes.append("\(file.path): add @SceneStorage for selection/scroll so the fold transition keeps user state.")
                }
            }
        }
        return Patch(transformId: "state-preservation", title: "State preservation across fold transitions",
            tier: .manual, edits: [], newFiles: [:],
            notes: notes.isEmpty ? ["No list/scroll views detected — nothing to do."] : notes + [
                "Pattern: @SceneStorage(\"selection\") var selection: String? — survives the scene geometry change.",
            ])
    }

    static func dehardcodeFrames(_ input: TransformInput) -> Patch {
        var notes: [String] = []
        let frameRe = try? NSRegularExpression(pattern: #"\.frame\(width:\s*\d+\.?\d*[a-zA-Z]*\s*,\s*height:\s*\d+\.?\d*[a-zA-Z]*"#, options: [])
        for file in input.swiftFiles {
            if let frameRe {
                let count = frameRe.numberOfMatches(in: file.content, range: NSRange(file.content.startIndex..., in: file.content))
                if count > 0 { notes.append("\(file.path): \(count) hardcoded frame(s) — prefer .containerRelativeFrame, GeometryReader, or intrinsic sizes.") }
            }
        }
        return Patch(transformId: "dehardcode-frames", title: "De-hardcode fixed frames",
            tier: .manual, edits: [], newFiles: [:],
            notes: notes.isEmpty ? ["No hardcoded frames detected."] : notes)
    }

    // MARK: - Helpers

    static func matchingCloseBrace(_ s: String, openBrace: String.Index) -> String.Index? {
        var depth = 0
        var inString = false
        var escape = false
        var i = s.index(after: openBrace)
        while i < s.endIndex {
            let c = s[i]
            if inString {
                if escape { escape = false }
                else if c == "\\" { escape = true }
                else if c == "\"" { inString = false }
            } else {
                if c == "\"" { inString = true }
                else if c == "{" { depth += 1 }
                else if c == "}" {
                    if depth == 0 { return i }
                    depth -= 1
                }
            }
            i = s.index(after: i)
        }
        return nil
    }

    static func matches(_ regex: NSRegularExpression?, _ s: String) -> Bool {
        guard let regex else { return false }
        return regex.firstMatch(in: s, range: NSRange(s.startIndex..., in: s)) != nil
    }
}
